### ISSUE TITLE
Add unit-tests

### ISSUE THREAD

**Issue by postmodern** [trailofbits/pe-parse#1]
All code must have tests.

**Comment by jkolek** [comment]
Is there an unit testing framework that you would prefer?

**Comment by dguido** [comment]
Let's come back to this issue later. We will probably want to setup an archive of PE files and host them on S3, then run pe-parse on them.

**Comment by woodruffw** [comment]
Revisiting this: I put together a zero-config googletest harness for [uthenticode](https://github.com/trailofbits/uthenticode) that we could reuse here.

We also have now have [pegoat](https://github.com/trailofbits/pegoat) with daily auto-builds for a suite of PE binaries.

**Comment by woodruffw** [comment]
We'll close this with #145, since it'll add an initial test suite. Coverage refinements can be handled by subsequent issues and PRs.
