### ISSUE TITLE
Remove Boost dependency

### ISSUE THREAD

**Issue by feliwir** [trailofbits/pe-parse#10]
As far as i see the boost library isn't required for the most parts (as C++ 11 does have most functionality that is used by this library). The problem with boost is, that it is a huge dependency and makes it very difficult to build this library on windows (eventhough it isn't too big of an issue for linux...). Instead of using boost integers i suggest going with stdint.h as it is available on every modern compiler. Other functionality can be replaced aswell by c++ 11 standard.
With best regards

**Comment by dguido** [comment]
Closed by #28
