### ISSUE TITLE
Disable warning while ParsePEFromFile

### ISSUE THREAD

**Issue by pol4bear** [trailofbits/pe-parse#106]
Hi! I want to disable Warning message while using ParsePEFromFile. When I call ParsePEFromFile messages below are printed at stdout. Is there any way that I can disable these messages?
```
Warning: Skipping auxiliary symbol of type CLASS_EXTERNAL at offset 0x76fc
Warning: Skipping auxiliary symbol of type CLASS_EXTERNAL at offset 0x7888
Warning: Skipping auxiliary symbol of type CLASS_EXTERNAL at offset 0x78f4
Warning: Skipping auxiliary symbol of type CLASS_EXTERNAL at offset 0x7960
Warning: Skipping auxiliary symbol of type CLASS_EXTERNAL at offset 0x7edc
Warning: Skipping auxiliary symbol of type CLASS_EXTERNAL at offset 0x7fb4
Warning: Invalid internal offset (current: 0x8c8a, expected: 0x8c92)
Warning: Invalid internal offset (current: 0x93a4, expected: 0x93ac)
```

**Comment by woodruffw** [comment]
Hmm, not currently. These are the lines in question:

https://github.com/trailofbits/pe-parse/blob/bd68ba418f2a9099dfc28fa1ea2e7b3f74e0917b/pe-parser-library/src/parse.cpp#L2296-L2322

These aren't fatal errors, so they don't get reported via pe-parse's normal error reporting API. I'd be okay with macro-gating them off (e.g., adding something like `PEPARSE_NO_WARNINGS` that can be configured at build time).
