### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Triangleowl** [trailofbits/pe-parse#109]
Hi, I tested your project with _test1.exe_ and got a segmentation fault.
[test1.zip](https://github.com/trailofbits/pe-parse/files/4304408/test1.zip)

**Comment by woodruffw** [comment]
Thanks @Triangleowl! I'll triage this today.

**Comment by Triangleowl** [comment]
Could you please request a CVE from GitHub using the [Security Advisory feature](https://help.github.com/en/github/managing-security-vulnerabilities/publishing-a-security-advisory#requesting-a-cve-identification-number) for me?
Thanks @woodruffw

**Comment by woodruffw** [comment]
> Could you please request a CVE from GitHub using the [Security Advisory feature](https://help.github.com/en/github/managing-security-vulnerabilities/publishing-a-security-advisory#requesting-a-cve-identification-number) for me?

A CVE will be contingent on the nature and scope of the fault. pe-parse is mostly used in research code and doesn't necessarily meet the requirements for a CVE.

**Comment by Triangleowl** [comment]
Thanks anyway!

**Comment by woodruffw** [comment]
No problem. Can you give me some details on where you got `test1.exe` from? I've root-caused it down to a malformed `bounded_buffer` when trying to grab the name of a module in an import directory entry:

```c++
      auto nameOff = static_cast<std::uint32_t>(name - nameSec.sectionBase);
      std::string modName;
      if (!readCString(*nameSec.sectionData, nameOff, modName)) {
        return false;
      }
```

**Comment by Triangleowl** [comment]
Honestly, I got it from a fuzz testing.

**Comment by woodruffw** [comment]
> Honestly, I got it from a fuzz testing.

Okay, thanks anyways. It looks like it's probably an incorrect assumption in `getSecForVA`, continuing to diagnose. For reference, the problematic VA is 0x140000000.

**Comment by woodruffw** [comment]
Further root causing: the section at that VA claims to have a way larger size than it should, so we probably calculate the bounded buffer incorrectly:

```
      _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7f54eb9075d8 "@"}, _M_string_length = 1, {
        _M_local_buf = "@", '\000' <repeats 14 times>, _M_allocated_capacity = 64}},
    sectionBase = 5368709120, sectionData = 0x0, sec = {Name = "@\000\000\300.pda", Misc = {
        PhysicalAddress = 3957108, VirtualSize = 3957108}, VirtualAddress = 0, SizeOfRawData = 134217728,
      PointerToRawData = 1, PointerToRelocations = 80, PointerToLinenumbers = 2, NumberOfRelocations = 38,
      NumberOfLinenumbers = 0, Characteristics = 0}}}
```

**Comment by woodruffw** [comment]
Yep: we pass the expected range based on that bad size to `splitBuffer`, which correctly detects that it's a nonsensical size and returns `nullptr`. We then fail to actually check for that `nullptr`, causing the segfault. Will test a fix in a moment.

**Comment by woodruffw** [comment]
Opened #110 with the fix.
