### ISSUE TITLE
Package with fpm

### ISSUE THREAD

**Issue by dguido** [trailofbits/pe-parse#11]
https://github.com/jordansissel/fpm

**Comment by layderv** [comment]
Does this involve changing travis.sh/cmake?

**Comment by woodruffw** [comment]
> Does this involve changing travis.sh/cmake?

I don't believe so.

**Comment by layderv** [comment]
Any idea on how you would like to see this?

**Comment by woodruffw** [comment]
> Any idea on how you would like to see this?

Hmm, I'm not actually sure. I think what we actually want here is just to have `pe-parse` available in a bunch of common package formats (e.g., `deb` and `rpm`), *not* necessarily via FPM specifically. 

I know we've used [CPack](https://cmake.org/cmake/help/v3.12/module/CPack.html) for packaging before and, given that we're already using CMake for the build, it might be simpler to integrate than FPM.

**Comment by layderv** [comment]
Sorry, I think it needs another thought.

**Comment by woodruffw** [comment]
pe-parse is packaged with vcpkg now, which I think is sufficient for the time being.
