### ISSUE TITLE
Publish a stable pe-parse release

### ISSUE THREAD

**Issue by woodruffw** [trailofbits/pe-parse#112]
We haven't been versioning pe-parse. It's pretty stable, so we should cut a release.

We should also publish `pepy` to PyPI and pin its release version to that of the rest of pe-parse.

See #105.

**Comment by woodruffw** [comment]
#113 performs the prep work for this. Will close when we cut a stable release.

**Comment by ekilmer** [comment]
I think we should try to include at least one (1) `.exe` file before the 1.0 release, just to make sure that everything is linked properly and nothing obvious slips by for all platforms.

The tests should, in my opinion, include the minimum of running 
```
python pepy/test.py <exe>
```
and
```
./build/dump-pe/dump-pe <exe>
```
where both should return a 0 exit code.

**Comment by woodruffw** [comment]
SGTM! I’ll take care of that tomorrow.
