### ISSUE TITLE
dump-pe gives error when parsing CLI options

### ISSUE THREAD

**Issue by ekilmer** [trailofbits/pe-parse#115]
First found when trying:
```
$ dump-pe --version
Error: 7 (Unable to open)
Location: readFileToFileBuffer:217
```
Also happens with `dump-pe --something`.

These lines aren't processing the arguments correctly:
https://github.com/trailofbits/pe-parse/blob/05676c1bf8f44231436aaf284534a4ff3d697d5f/dump-pe/main.cpp#L294-L302

Side-note: It would be nice to have `--version` print the version of the pe-parse-library.

**Comment by woodruffw** [comment]
Yep, agreed. We should use `getopt` or another standard solution here.

**Comment by woodruffw** [comment]
Let's use `argh` here, since it worked well for uthenticode: https://github.com/adishavit/argh

We can put it in a `vendor` subdirectory under `dump-pe`.
