### ISSUE TITLE
Please consider using shorter/consistent names for library name / include directory.

### ISSUE THREAD

**Issue by hillu** [trailofbits/pe-parse#134]
When installing pe-parse on *nix systems, I noticed that headers get installed into `PREFIX/include/parser-library` and the library is named `libpe-parser-library`. This looks odd. ;-)

1. `parser-library` is pretty generic, the name as used in ```#include <parser-library/parse.h>``` does not tell the reader anything what this is about. 
2. There is no need for the `-library` suffix in the library name?

How about using `pe-parser` in both cases?

**Comment by woodruffw** [comment]
Thanks @hillu! I agree completely, and this is an important refactor we need to perform for the next release.
