### ISSUE TITLE
dump-pe shows all PE32/PE32+ 64 bits 

### ISSUE THREAD

**Issue by liujian883** [trailofbits/pe-parse#135]
hello
From the README documentation, I know that VS2017 and VS2019 are supported.I compiled with VS2015. I tested with dump-pe.exe and found that the PE files(32 and 64 bit) all showed up as 64bit.Is this due to the VS2015 compiler? Thanks!

**Comment by woodruffw** [comment]
> Is this due to the VS2015 compiler?

Possibly. It's hard to tell without more information. Could you confirm that you're building on the latest master, and upload the file that you're testing with `dump-pe.exe`? Alternatively, if you can't share the EXE, can you share the relevant parts of `dump-pe.exe`'s output?

**Comment by woodruffw** [comment]
Feel free to reopen this once you have a sample or a test case for reproduction. I haven't seen anything like this in practice and we've successfully used pe-parse on both PE32s and PE32+s without ambiguity, so I suspect this is a build configuration issue.
