### ISSUE TITLE
Not able to execute dump-prog

### ISSUE THREAD

**Issue by arezafar** [trailofbits/pe-parse#15]
Hi,

I have tried to get pe-parse working on a mac and rhel/fedora, in both cases the dump-prog program crashes. 

Here is the output on linux:
[ec2-user@ip-10-35-66-166 dump-prog]$ make;./dump-prog "/home/ec2-user/pe/pe-parse/dump-prog/putty.exe"
[ 66%] Built target pe-parser-library
[100%] Building CXX object dump-prog/CMakeFiles/dump-prog.dir/dump.cpp.o
Linking CXX executable dump-prog
[100%] Built target dump-prog
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
Aborted

Here is the output on osx:
arezafar@Alis-MacBook-Pro:dump-prog [master]$ make;./dump-prog "../../putty.exe"
Scanning dependencies of target pe-parser-library
[ 33%] Building CXX object parser-library/CMakeFiles/pe-parser-library.dir/buffer.cpp.o
[ 66%] Building CXX object parser-library/CMakeFiles/pe-parser-library.dir/parse.cpp.o
Linking CXX static library libpe-parser-library.a
[ 66%] Built target pe-parser-library
Scanning dependencies of target dump-prog
[100%] Building CXX object dump-prog/CMakeFiles/dump-prog.dir/dump.cpp.o
Linking CXX executable dump-prog
[100%] Built target dump-prog
Segmentation fault: 11

![screen shot 2015-02-27 at 7 28 43 am](https://cloud.githubusercontent.com/assets/2983009/6415197/52c994f8-be52-11e4-94cb-511a506e6277.png)

In both cases it seems to be a basic string library issue, how could I get around it?

Thanks,
Ali

**Comment by dguido** [comment]
I was able to reliably reproduce this on OSX with the following exe:
http://the.earth.li/~sgtatham/putty/latest/x86/putty.exe
