### ISSUE TITLE
CONTRIBUTING.md deserves an update!!!

### ISSUE THREAD

**Issue by HimanshuMahto** [trailofbits/pe-parse#195]
Unlike other amazing repos, this repo's CONTRIBUTING.md looks plain and simple.

i think emojified, fun and precise version would be better!

Describe alternatives you've considered
An update would be amazing!

Additional context
If you are reading this, you are amazing! ⭐

Starred ⭐✔️

Thanks and regards,
Himanshu.

**Comment by woodruffw** [comment]
Thanks for the offer, but I think we'd prefer to keep it concise and strictly informational.

If there are *specific* missing pieces of information, please feel free to contribute them. Otherwise, we're unlikely to accept PRs that just update the formatting.
