### ISSUE TITLE
the parse lib is not thread safe

### ISSUE THREAD

**Issue by mathieuwolf** [trailofbits/pe-parse#202]
Hi,
There is a race read/write on global std::string err_loc in parse.cpp
https://github.com/trailofbits/pe-parse/blob/f2f0ee91f3b6dee41f75b2f775e82015f2b72007/pe-parser-library/src/parse.cpp#L484
and

https://github.com/trailofbits/pe-parse/blob/f2f0ee91f3b6dee41f75b2f775e82015f2b72007/pe-parser-library/include/pe-parse/parse.h#L38-L41

This is probably a CVE for application using this lib in multithreading scenario (multiple threads parse different buffers/files at the same time).
Can be mitigated by declaring the variable thread_local, but the err has to be retrieved from the same thread.
Mathieu

**Comment by woodruffw** [comment]
> This is probably a CVE for application using this lib in multithreading scenario (multiple threads parse different buffers/files at the same time).

As far as I know (I'm not the original author), this library wasn't ever intended to be used in a multi-threaded setting. If you want to multi-thread it, you'll need to add a subsequent layer of locking and/or synchronization above it.

(I agree that this is a bug, but I'm not sure an attacker can do anything useful with an unsynchronized error value shared across threads in this case -- I suppose they could cause an unrelated PE parse to fail, but that presumes they already control an invalid PE.)

**Comment by woodruffw** [comment]
Added to the README: https://github.com/trailofbits/pe-parse/commit/31ac5966503689d5693cd9fb520bd525a8710e17

**Comment by mathieuwolf** [comment]
Thank you very much
