### ISSUE TITLE
Segmentation fault in get_bytes

### ISSUE THREAD

**Issue by xulifan** [trailofbits/pe-parse#25]
from test.py:
byts = p.get_bytes(ep, 8)

I got segmentation fault in this function. 
Here is my output:

[lxu@static1 python]$ python test.py /home/nfs/lxu/data/PE_binary/00001AA4444F539C1B63C4B4BECE8BA374757FEC49C17D218B6339EFD3EAA491 
Magic: 0x10b
Signature: 0x4550
Machine: 0x14c
Number of sections: 3
Number of symbols: 0
Characteristics: 0x210e
Timedatestamp: 2006-12-26 06:48:21
Major linker version: 0x6
Minor linker version: 0x0
Size of code: 0xc7000
Size of initialized data: 0x2000
Size of uninitialized data: 0x0
Address of entry point: 0xc8fbe
Base address of code: 0x2000
Base address of data: 0xca000
Image base address: 0x45d60000
Section alignment: 0x2000
File alignment: 0x1000
Major OS version: 0x4
Minor OS version: 0x0
Win32 version: 0x0
Size of image: 0xce000
Size of headers: 0x1000
Checksum: 0xcde81
Subsystem: 0x3
DLL characteristics: 0x400
Size of stack reserve: 0x100000
Size of stack commit: 0x1000
Size of heap reserve: 0x100000
Size of heap commit: 0x1000
Loader flags: 0x0
Number of RVA and sizes: 0x10
Get entry point
Get bytes
Segmentation fault (core dumped)

**Comment by artemdinaburg** [comment]
Are you able to share the file thats causing the issue?

**Comment by xulifan** [comment]
Hi, since github does not support attaching PE file, the file is attached in the zip file. Please unzip it to get the file.

[00001AA4444F539C1B63C4B4BECE8BA374757FEC49C17D218B6339EFD3EAA491.zip](https://github.com/trailofbits/pe-parse/files/815202/00001AA4444F539C1B63C4B4BECE8BA374757FEC49C17D218B6339EFD3EAA491.zip)

**Comment by artemdinaburg** [comment]
Thanks for submitting this issue! The cause was that the global `err` symbol was also defined in Python as a function, and it would override the definition of `err` in pe-parse. When peparse would try to write to `err`, it would crash as executable code pages are non-writable. 

The fix in PR #26 is to put peparse into its own namespace. I tested and it fixes the issue with this file.
