### ISSUE TITLE
relocation information calculate wrong

### ISSUE THREAD

**Issue by mwpcheung** [trailofbits/pe-parse#32]
at file parse.cpp line 1067.. the original code is:
    //iter over all of the blocks
    ::uint32_t  blockCount = blockSize/sizeof(::uint16_t);

the blockSize should minus  8.
//iter over all of the blocks
::uint32_t  blockCount = (blockSize - 8) / sizeof(::uint16_t);

therefore the pe file has many blocks of relocs. reloc block is end of
pageRva = 0 and rvaofft = 0.

**Comment by dguido** [comment]
Closed by #39

**Comment by mwpcheung** [comment]
thk u, thnks for ur exernlent work
