### ISSUE TITLE
Windows 7 build

### ISSUE THREAD

**Issue by ANeeK181** [trailofbits/pe-parse#37]
Hi

How can I build it for Windows 7 32-bit using VS2015. I generate the project but there is linking error of unistd which is a unix specific file.

Regards

**Comment by jkolek** [comment]
https://github.com/trailofbits/pe-parse/pull/38

**Comment by ANeeK181** [comment]
Thanks, it's working now for Windows 7 32-bit with Visual Studio 2015.
