### ISSUE TITLE
Documentation request: Comparing of resource names is not obvious

### ISSUE THREAD

**Issue by Ghabry** [trailofbits/pe-parse#43]
I tried to extract a specific resource, lets call it "ABCD" out of an exe, so I used the dumper as a reference:

```cpp
int printRsrc(void *N, resource r) {
  if (r.name_str.length())
    cout << "Name (string): " << r.name_str << endl;
  return 0;
}
```

Output: ``Name (string): ABCD`` (as expected)

Then I replaced the code with
```cpp
int printRsrc(void *N, resource r) {
  if (r.name_str == "ABCD")
    // print something
```
And wondered why it never enters the if-block, also the debugger only showed "A" and I wondered whats going because it's a normal std::string and std::cout was somehow able to print it properly.

After 30min of confusion I noticed that these are UTF-16 strings (obviously, that's Windows) and that "std::cout" silently swallows 0-bytes instead of echoing \0.

So for C++11 one way to do it is e.g.:

```cpp
if (r.name_str.length() == 8 && !memcmp(u"ABCD", r.name_str.c_str(), 8))
```

Could a note about this be added somewhere? I assume this also confuses other devs for a few minutes :)

**Comment by pgoodman** [comment]
It seems like the `name_str` should really be a `std::wstring`, which lacks and `operator==` and therefore requires one to use `std::wstring::compare`, which I thing is self-documenting.

**Comment by pgoodman** [comment]
Whoops it does have the usual relational operators, just not at methods. Anyway, I think `std::wstring` should be used. I'm not a fan of the suggested usage of `memcmp`.

**Comment by Ghabry** [comment]
Of course a type change is even better then that ugly memcmp workaround I suggested. 

Because the code is c++11 the best option is std::u16string which is 16 bit everywhere because wstring is using platform dependend wchar_t (16 bit on Windows, 32 bit on Linux).

**Comment by pgoodman** [comment]
Oh neat, I didn't know about `std::u16string`. I await a PR.

**Comment by roachspray** [comment]
Per discussion: fairly obtuse solution with changing to u16string and doing string conversion in the code using the library. Not sure if this is the way to go...maybe want to put into to_string or some such. That being said, maybe there are other issues. Submitting anyway to push forward.
