### ISSUE TITLE
Unable to parse pe image generated by mingw gcc

### ISSUE THREAD

**Issue by a-v-s** [trailofbits/pe-parse#65]
I am using ArchLinux. I have built pe-parse using the supplied PKGBUILD file.
I have installed mingw-w64-gcc-bin 7.3.0-1 from AUR.

`$ x86_64-w64-mingw32-gcc hello.c -o hello.exe`
`$ dump-pe hello.exe`
`Error: 9 (Bad magic)`
`Location: getSymbolTable:1375`
`$ file hello.exe`
`hello.exe: PE32+ executable (console) x86-64, for MS Windows`

[hello.zip](https://github.com/trailofbits/pe-parse/files/1899133/hello.zip)

**Comment by alessandrogario** [comment]
Hello @a-v-s ,

Thanks for taking the time to open the issue! The sample you provided was extremely useful in helping me discover and fix the bug.

I have created a new branch that contains a correction for the problem; the major issue was that the file offset and the symbol counter were not being correctly incremented when parsing auxiliary symbols in the symbols table.

The PR can be found here: https://github.com/trailofbits/pe-parse/pull/66
