### ISSUE TITLE
Populate Rich header product names

### ISSUE THREAD

**Issue by stefansiegfried** [trailofbits/pe-parse#93]
The Rich header parser contains a map of build numbers to product names that needs to be populated. See peparse::ProductMap.

Each Rich header entry is made up of a product id, a build number, and a count of the number of objects of that type.  The build number can be used to almost uniquely identify the product name and version used to create that object.

Useful references of mapping information:
http://bytepointer.com/articles/the_microsoft_rich_header.htm
https://github.com/dishather/richprint/blob/master/comp_id.txt
https://walbourn.github.io
https://dev.to/yumetodo/list-of-mscver-and-mscfullver-8nd

**Comment by woodruffw** [comment]
#94.
