### ISSUE TITLE
Identifier/macro collisions with Windows.h

### ISSUE THREAD

**Issue by woodruffw** [trailofbits/pe-parse#98]
Including both `parse.h` and `Windows.h` in the same translation unit leads to hellish compilation errors, presumably because `Windows.h` defines `IMAGE_FILE_*` as macros and namespaces can't mask those.

Some potential solutions:

* Provide official guidance to *not* use `Windows.h` and `parse.h` in the same source file
* Prefix all of our duplicated constants

See #69

**Comment by stevemk14ebr** [comment]
Officially requiring people don't use windows.h is not a good idea IMHO. There's significant functionality provided by that header AND it's likely to be used in projects that require PE parsing.

**Comment by woodruffw** [comment]
> Officially requiring people don't use windows.h is not a good idea IMHO. There's significant functionality provided by that header AND it's likely to be used in projects that require PE parsing.

This is true! It's also not what I said above: the official guidance would be to not include both *in the same source file*. As far as I know, quarantining inclusion of `Windows.h` to as few source files as possible is already common practice in large codebases (for both conflict and performance reasons).

**Comment by stevemk14ebr** [comment]
Ah I see. I stand by my opinion. The problems are in this library choosing to duplicate common headers. No matter the reason why, that is the source of errors and should be fixed there. But I recognize this is an opinion, do as you wish.
